### ISSUE TITLE
Gate Authorization

### ISSUE THREAD

**Issue by overtrue** [overtrue/wisteria#3]

**Comment by saleem-hadad** [comment]
All the best 👍 😁 @overtrue

**Comment by overtrue** [comment]
@saleem-hadad 🤣 Thank you.

**Comment by overtrue** [comment]
@saleem-hadad Try this demo: https://www.easywechat.com/docs

**Comment by saleem-hadad** [comment]
Pretty Cool! 👍🤓
I'm happy for you dude, but I found it interesting haha

**Comment by overtrue** [comment]
haha

**Comment by saleem-hadad** [comment]
Good luck 😎

**Comment by overtrue** [comment]
@saleem-hadad I think you have something to say？

**Comment by saleem-hadad** [comment]
Of course not dude 😂sorry I think you got me wrong
I'm really happy to see my code used by other devs, in fact, we all share, learn and get benefits of each other 😍👍

**Comment by overtrue** [comment]
@saleem-hadad haha, so did you meaning these lines ? 

https://github.com/overtrue/wisteria/blob/master/src/Commands/InstallCommand.php#L39-L47

First of all, thank you for your contribution. I did read your code carefully before writing this package, and the copy of the installation command is what you wrote, but the other part does not use your code. 😂

**Comment by saleem-hadad** [comment]
I apologise dude I'm afraid you get me wrong but really I didn't mean anything ❤️ I'm going to delete my comments cus I see the conversation going to another dimension

**Comment by overtrue** [comment]
```php
Gate::define('wisteria.view', function($user = null, $v, $c){
    return true;
});
```
